spring:
  application:
    name: backend
  datasource:
#    url: jdbc:mysql://mysql-furia:3306/furia
    url: jdbc:mysql://localhost:3307/furia
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    #      ddl-auto: none
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
twitch:
  client-id: ${TWITCH_CLIENT_ID}
  client-secret: ${TWITCH_CLIENT_SECRET}
  redirect-uri: ${TWITCH_REDIRECT_URI}
